/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OurVisionRouteImport } from './routes/our-vision'
import { Route as OrderConfirmationRouteImport } from './routes/order-confirmation'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorldSlugRouteImport } from './routes/world.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'

const OurVisionRoute = OurVisionRouteImport.update({
  id: '/our-vision',
  path: '/our-vision',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order-confirmation',
  path: '/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldSlugRoute = WorldSlugRouteImport.update({
  id: '/world/$slug',
  path: '/world/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/our-vision': typeof OurVisionRoute
  '/product/$slug': typeof ProductSlugRoute
  '/world/$slug': typeof WorldSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/our-vision': typeof OurVisionRoute
  '/product/$slug': typeof ProductSlugRoute
  '/world/$slug': typeof WorldSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/our-vision': typeof OurVisionRoute
  '/product/$slug': typeof ProductSlugRoute
  '/world/$slug': typeof WorldSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/order-confirmation'
    | '/our-vision'
    | '/product/$slug'
    | '/world/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/order-confirmation'
    | '/our-vision'
    | '/product/$slug'
    | '/world/$slug'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/order-confirmation'
    | '/our-vision'
    | '/product/$slug'
    | '/world/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  OurVisionRoute: typeof OurVisionRoute
  ProductSlugRoute: typeof ProductSlugRoute
  WorldSlugRoute: typeof WorldSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/our-vision': {
      id: '/our-vision'
      path: '/our-vision'
      fullPath: '/our-vision'
      preLoaderRoute: typeof OurVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation': {
      id: '/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/$slug': {
      id: '/world/$slug'
      path: '/world/$slug'
      fullPath: '/world/$slug'
      preLoaderRoute: typeof WorldSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  OurVisionRoute: OurVisionRoute,
  ProductSlugRoute: ProductSlugRoute,
  WorldSlugRoute: WorldSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
